- hosts: localhost
  become: yes
  tasks:
    - name: Update repositories cache and install "java" package
      apt:
        name: openjdk-11-jre-headless
        update_cache: yes
      become: true

    - name: add group "tomcat"
      group: name=tomcat
      become: true

    - name: Create home directory for tomcat
      file:
        path: /opt/tomcat/
        state: directory
        mode: 0755
        recurse: yes
      become: true

    - name: add user "tomcat"
      user: name=tomcat group=tomcat home=/opt/tomcat shell=/sbin/nologin createhome=no
      become: true

    - name: Extract tomcat
      unarchive:
        src: "https://apache.osuosl.org/tomcat/tomcat-9/v9.0.33/bin/apache-tomcat-9.0.33.tar.gz"
        dest: "/opt/tomcat/"
        remote_src: True
      become: true

    - name: Symlink install directory
      file: src=/opt/apache-tomcat-9.0.33 path=/usr/share/tomcat state=link

    - name: Change ownership of Tomcat installation
      file: path=/usr/share/tomcat/ owner=tomcat group=tomcat state=directory recurse=yes

    - name: Configure Tomcat server
      template: src=/ansible/tomcat/server.xml dest=/usr/share/tomcat/conf/
      notify: restart tomcat
    
    - name: Configure Tomcat users
      template: src=/ansible/tomcat/tomcat-users.xml dest=/usr/share/tomcat/conf/
      notify: restart tomcat

    - name: start tomcat
      command: /opt/tomcat/apache-tomcat-9.0.33/bin/startup.sh
      become: true

    - name: copy the jar to lib directory
      copy:
        src:  /my-app-1.0.0-SNAPSHOT.jar
        dest: /home/ubuntu/apache-tomcat-9.0.33/lib/

    - name: start tomcat
      command: /opt/tomcat/apache-tomcat-9.0.33/bin/startup.sh
      become: true
    
  handlers:
    - name: restart tomcat
      service:
        name: tomcat
        state: restarted
